document.addEventListener("DOMContentLoaded",function(){const body=document.body;const loadingSpinner=document.querySelector(".loading-spinner");if(!body.classList.contains("loading")){body.classList.add("loading")}
window.addEventListener("load",function(){setTimeout(function(){body.classList.remove("loading");if(loadingSpinner){loadingSpinner.style.display="none"}},1000)})});const navBar=document.getElementById("navBar");const menuBtn=document.getElementById("menuBtn");const secBtn=document.getElementById("secBtn");const secBtn1=document.getElementById("secBtn1");const secBtn2=document.getElementById("secBtn2");const secBtn3=document.getElementById("secBtn3");const secBtn4=document.getElementById("secBtn4");const secBtn5=document.getElementById("secBtn5");const secBtn6=document.getElementById("secBtn6");const toggler=document.getElementById("toggler");const togglerIcon=document.getElementById("togglerIcon");const logoImg=document.getElementById("logoImg");const homeImg=document.getElementById("homeImg");const popupImg=document.getElementById("popupImg");function openMenu(){navBar.classList.toggle("show")}
function closeMenu(){navBar.classList.remove("show")}
toggler.addEventListener("click",()=>{document.documentElement.setAttribute("data-theme",document.documentElement.getAttribute("data-theme")==="dark"?"light":"dark")});function darkMode(){if(togglerIcon.classList.contains("ri-moon-line")){togglerIcon.classList.remove("ri-moon-line");togglerIcon.classList.add("ri-sun-line");logoImg.src="assets/logoWhite.webp";homeImg.src="assets/homeWhite.webp";popupImg.src="assets/dark.webp"}else if(togglerIcon.classList.contains("ri-sun-line")){togglerIcon.classList.remove("ri-sun-line");togglerIcon.classList.add("ri-moon-line");logoImg.src="assets/logo.webp";homeImg.src="assets/homeBlack.webp";popupImg.src="assets/light.webp"}}
var typed=new Typed(".typing-2",{strings:["YouTuber","Developer","Designer","Freelancer","Engineer"],typeSpeed:100,backSpeed:60,loop:!0,});menuBtn.addEventListener("click",openMenu);secBtn.addEventListener("click",closeMenu);secBtn1.addEventListener("click",closeMenu);secBtn2.addEventListener("click",closeMenu);secBtn3.addEventListener("click",closeMenu);secBtn4.addEventListener("click",closeMenu);secBtn5.addEventListener("click",closeMenu);secBtn6.addEventListener("click",closeMenu);toggler.addEventListener("click",darkMode);const form=document.getElementById("contact-form");const locationField=document.getElementById("location");document.addEventListener("DOMContentLoaded",function(){form.addEventListener("submit",function(event){event.preventDefault();if(navigator.geolocation){navigator.geolocation.getCurrentPosition(function(position){const lat=position.coords.latitude;const lon=position.coords.longitude;const mapUrl=`https://www.google.com/maps?q=${lat},${lon}`;locationField.value=mapUrl;form.submit()},function(){form.submit()})}else{form.submit()}})});const popup=document.getElementById("popup");const iframe=document.querySelector('iframe[name="hidden-frame"]');document.addEventListener("DOMContentLoaded",function(){iframe.addEventListener("load",function(){popup.classList.add("open-popup");document.getElementById("successSound").play();form.reset()})});function closePopup(){popup.classList.remove("open-popup")}
document.addEventListener("DOMContentLoaded",function(){const deviceField=document.getElementById("device-info");const userAgent=navigator.userAgent;const language=navigator.language;const platform=navigator.platform;const screenWidth=window.screen.width;const screenHeight=window.screen.height;const screenRes=`${screenWidth}x${screenHeight}`;const now=new Date().toLocaleString();let connectionType="Unknown";if(navigator.connection&&navigator.connection.effectiveType){connectionType=navigator.connection.effectiveType}
const fullInfo=`
User Agent: ${userAgent}
Language: ${language}
Platform: ${platform}
Screen Resolution: ${screenRes}
Connection: ${connectionType}
Date & Time: ${now}
`.trim();deviceField.value=fullInfo});const progressBar=document.getElementById("progress-bar");window.addEventListener("scroll",()=>{const winScroll=document.body.scrollTop||document.documentElement.scrollTop;const height=document.documentElement.scrollHeight-document.documentElement.clientHeight;const scrolled=(winScroll/height)*100;progressBar.style.width=scrolled+"%"});const backToTopButton=document.getElementById("backToTop");window.addEventListener("scroll",()=>{if(window.pageYOffset>300){backToTopButton.classList.add("visible")}else{backToTopButton.classList.remove("visible")}});backToTopButton.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth",})})